// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: fenix.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_fenix_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "running", "stopped", "error", "starting"
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_fenix_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ListModulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesRequest) Reset() {
	*x = ListModulesRequest{}
	mi := &file_fenix_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesRequest) ProtoMessage() {}

func (x *ListModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesRequest.ProtoReflect.Descriptor instead.
func (*ListModulesRequest) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{2}
}

type ListModulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*ModuleStatus        `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesResponse) Reset() {
	*x = ListModulesResponse{}
	mi := &file_fenix_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesResponse) ProtoMessage() {}

func (x *ListModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesResponse.ProtoReflect.Descriptor instead.
func (*ListModulesResponse) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{3}
}

func (x *ListModulesResponse) GetModules() []*ModuleStatus {
	if x != nil {
		return x.Modules
	}
	return nil
}

type GetModuleStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleStatusRequest) Reset() {
	*x = GetModuleStatusRequest{}
	mi := &file_fenix_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleStatusRequest) ProtoMessage() {}

func (x *GetModuleStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleStatusRequest.ProtoReflect.Descriptor instead.
func (*GetModuleStatusRequest) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{4}
}

func (x *GetModuleStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ModuleStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "running", "stopped", "error", "starting"
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleStatus) Reset() {
	*x = ModuleStatus{}
	mi := &file_fenix_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleStatus) ProtoMessage() {}

func (x *ModuleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleStatus.ProtoReflect.Descriptor instead.
func (*ModuleStatus) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{5}
}

func (x *ModuleStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleStatus) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ModuleStatus) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModuleStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ModuleStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ModuleStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UIStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIStreamRequest) Reset() {
	*x = UIStreamRequest{}
	mi := &file_fenix_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIStreamRequest) ProtoMessage() {}

func (x *UIStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIStreamRequest.ProtoReflect.Descriptor instead.
func (*UIStreamRequest) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{6}
}

func (x *UIStreamRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type UIViewUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Components    []*UIComponent         `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	Actions       []*UIAction            `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIViewUpdate) Reset() {
	*x = UIViewUpdate{}
	mi := &file_fenix_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIViewUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIViewUpdate) ProtoMessage() {}

func (x *UIViewUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIViewUpdate.ProtoReflect.Descriptor instead.
func (*UIViewUpdate) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{7}
}

func (x *UIViewUpdate) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *UIViewUpdate) GetComponents() []*UIComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *UIViewUpdate) GetActions() []*UIAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type UIComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "header", "text_block", "table", "card", "metric_row", "chart", "list", "form", "action_bar", "status_bar"
	Level         *int32                 `protobuf:"varint,3,opt,name=level,proto3,oneof" json:"level,omitempty"`
	Content       *string                `protobuf:"bytes,4,opt,name=content,proto3,oneof" json:"content,omitempty"`
	Preformatted  *bool                  `protobuf:"varint,5,opt,name=preformatted,proto3,oneof" json:"preformatted,omitempty"`
	Columns       []*TableColumn         `protobuf:"bytes,6,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*RowData             `protobuf:"bytes,7,rep,name=rows,proto3" json:"rows,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,8,rep,name=metrics,proto3" json:"metrics,omitempty"`
	ChartType     *string                `protobuf:"bytes,9,opt,name=chart_type,json=chartType,proto3,oneof" json:"chart_type,omitempty"` // "area", "bar", "line", "pie"
	ChartData     []*ChartDataPoint      `protobuf:"bytes,10,rep,name=chart_data,json=chartData,proto3" json:"chart_data,omitempty"`
	Items         []string               `protobuf:"bytes,11,rep,name=items,proto3" json:"items,omitempty"`
	Fields        []*FormField           `protobuf:"bytes,12,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIComponent) Reset() {
	*x = UIComponent{}
	mi := &file_fenix_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIComponent) ProtoMessage() {}

func (x *UIComponent) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIComponent.ProtoReflect.Descriptor instead.
func (*UIComponent) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{8}
}

func (x *UIComponent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UIComponent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UIComponent) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *UIComponent) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UIComponent) GetPreformatted() bool {
	if x != nil && x.Preformatted != nil {
		return *x.Preformatted
	}
	return false
}

func (x *UIComponent) GetColumns() []*TableColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *UIComponent) GetRows() []*RowData {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *UIComponent) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *UIComponent) GetChartType() string {
	if x != nil && x.ChartType != nil {
		return *x.ChartType
	}
	return ""
}

func (x *UIComponent) GetChartData() []*ChartDataPoint {
	if x != nil {
		return x.ChartData
	}
	return nil
}

func (x *UIComponent) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UIComponent) GetFields() []*FormField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type TableColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Sortable      bool                   `protobuf:"varint,3,opt,name=sortable,proto3" json:"sortable,omitempty"`
	Width         *int32                 `protobuf:"varint,4,opt,name=width,proto3,oneof" json:"width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableColumn) Reset() {
	*x = TableColumn{}
	mi := &file_fenix_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableColumn) ProtoMessage() {}

func (x *TableColumn) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableColumn.ProtoReflect.Descriptor instead.
func (*TableColumn) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{9}
}

func (x *TableColumn) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TableColumn) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TableColumn) GetSortable() bool {
	if x != nil {
		return x.Sortable
	}
	return false
}

func (x *TableColumn) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

type RowData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowData) Reset() {
	*x = RowData{}
	mi := &file_fenix_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowData) ProtoMessage() {}

func (x *RowData) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowData.ProtoReflect.Descriptor instead.
func (*RowData) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{10}
}

func (x *RowData) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Trend         string                 `protobuf:"bytes,3,opt,name=trend,proto3" json:"trend,omitempty"` // "up", "down", "flat"
	ChangePercent float64                `protobuf:"fixed64,4,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_fenix_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{11}
}

func (x *Metric) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Metric) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Metric) GetTrend() string {
	if x != nil {
		return x.Trend
	}
	return ""
}

func (x *Metric) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

type ChartDataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChartDataPoint) Reset() {
	*x = ChartDataPoint{}
	mi := &file_fenix_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartDataPoint) ProtoMessage() {}

func (x *ChartDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartDataPoint.ProtoReflect.Descriptor instead.
func (*ChartDataPoint) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{12}
}

func (x *ChartDataPoint) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type FormField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	FieldType     string                 `protobuf:"bytes,3,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"` // "text", "number", "select", "checkbox", "password"
	Placeholder   *string                `protobuf:"bytes,4,opt,name=placeholder,proto3,oneof" json:"placeholder,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Options       []string               `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormField) Reset() {
	*x = FormField{}
	mi := &file_fenix_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormField) ProtoMessage() {}

func (x *FormField) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormField.ProtoReflect.Descriptor instead.
func (*FormField) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{13}
}

func (x *FormField) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FormField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FormField) GetFieldType() string {
	if x != nil {
		return x.FieldType
	}
	return ""
}

func (x *FormField) GetPlaceholder() string {
	if x != nil && x.Placeholder != nil {
		return *x.Placeholder
	}
	return ""
}

func (x *FormField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FormField) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type UIAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Shortcut      *string                `protobuf:"bytes,3,opt,name=shortcut,proto3,oneof" json:"shortcut,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIAction) Reset() {
	*x = UIAction{}
	mi := &file_fenix_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIAction) ProtoMessage() {}

func (x *UIAction) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIAction.ProtoReflect.Descriptor instead.
func (*UIAction) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{14}
}

func (x *UIAction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UIAction) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UIAction) GetShortcut() string {
	if x != nil && x.Shortcut != nil {
		return *x.Shortcut
	}
	return ""
}

func (x *UIAction) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UIEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	ActionId      *string                `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3,oneof" json:"action_id,omitempty"`
	ComponentId   *string                `protobuf:"bytes,3,opt,name=component_id,json=componentId,proto3,oneof" json:"component_id,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "click", "input", "shortcut", "scroll"
	Data          map[string]string      `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIEventRequest) Reset() {
	*x = UIEventRequest{}
	mi := &file_fenix_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIEventRequest) ProtoMessage() {}

func (x *UIEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIEventRequest.ProtoReflect.Descriptor instead.
func (*UIEventRequest) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{15}
}

func (x *UIEventRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *UIEventRequest) GetActionId() string {
	if x != nil && x.ActionId != nil {
		return *x.ActionId
	}
	return ""
}

func (x *UIEventRequest) GetComponentId() string {
	if x != nil && x.ComponentId != nil {
		return *x.ComponentId
	}
	return ""
}

func (x *UIEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *UIEventRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type UIEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIEventResponse) Reset() {
	*x = UIEventResponse{}
	mi := &file_fenix_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIEventResponse) ProtoMessage() {}

func (x *UIEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fenix_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIEventResponse.ProtoReflect.Descriptor instead.
func (*UIEventResponse) Descriptor() ([]byte, []int) {
	return file_fenix_proto_rawDescGZIP(), []int{16}
}

func (x *UIEventResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_fenix_proto protoreflect.FileDescriptor

const file_fenix_proto_rawDesc = "" +
	"\n" +
	"\vfenix.proto\x12\x05fenix\"\x14\n" +
	"\x12HealthCheckRequest\"\x88\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"\x14\n" +
	"\x12ListModulesRequest\"D\n" +
	"\x13ListModulesResponse\x12-\n" +
	"\amodules\x18\x01 \x03(\v2\x13.fenix.ModuleStatusR\amodules\",\n" +
	"\x16GetModuleStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xbe\x01\n" +
	"\fModuleStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\")\n" +
	"\x0fUIStreamRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\"\x85\x01\n" +
	"\fUIViewUpdate\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x122\n" +
	"\n" +
	"components\x18\x02 \x03(\v2\x12.fenix.UIComponentR\n" +
	"components\x12)\n" +
	"\aactions\x18\x03 \x03(\v2\x0f.fenix.UIActionR\aactions\"\xdf\x03\n" +
	"\vUIComponent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\x05level\x18\x03 \x01(\x05H\x00R\x05level\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x04 \x01(\tH\x01R\acontent\x88\x01\x01\x12'\n" +
	"\fpreformatted\x18\x05 \x01(\bH\x02R\fpreformatted\x88\x01\x01\x12,\n" +
	"\acolumns\x18\x06 \x03(\v2\x12.fenix.TableColumnR\acolumns\x12\"\n" +
	"\x04rows\x18\a \x03(\v2\x0e.fenix.RowDataR\x04rows\x12'\n" +
	"\ametrics\x18\b \x03(\v2\r.fenix.MetricR\ametrics\x12\"\n" +
	"\n" +
	"chart_type\x18\t \x01(\tH\x03R\tchartType\x88\x01\x01\x124\n" +
	"\n" +
	"chart_data\x18\n" +
	" \x03(\v2\x15.fenix.ChartDataPointR\tchartData\x12\x14\n" +
	"\x05items\x18\v \x03(\tR\x05items\x12(\n" +
	"\x06fields\x18\f \x03(\v2\x10.fenix.FormFieldR\x06fieldsB\b\n" +
	"\x06_levelB\n" +
	"\n" +
	"\b_contentB\x0f\n" +
	"\r_preformattedB\r\n" +
	"\v_chart_type\"v\n" +
	"\vTableColumn\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1a\n" +
	"\bsortable\x18\x03 \x01(\bR\bsortable\x12\x19\n" +
	"\x05width\x18\x04 \x01(\x05H\x00R\x05width\x88\x01\x01B\b\n" +
	"\x06_width\"x\n" +
	"\aRowData\x122\n" +
	"\x06values\x18\x01 \x03(\v2\x1a.fenix.RowData.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x06Metric\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x14\n" +
	"\x05trend\x18\x03 \x01(\tR\x05trend\x12%\n" +
	"\x0echange_percent\x18\x04 \x01(\x01R\rchangePercent\"\x86\x01\n" +
	"\x0eChartDataPoint\x129\n" +
	"\x06values\x18\x01 \x03(\v2!.fenix.ChartDataPoint.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\tFormField\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"field_type\x18\x03 \x01(\tR\tfieldType\x12%\n" +
	"\vplaceholder\x18\x04 \x01(\tH\x00R\vplaceholder\x88\x01\x01\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x18\n" +
	"\aoptions\x18\x06 \x03(\tR\aoptionsB\x0e\n" +
	"\f_placeholder\"x\n" +
	"\bUIAction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1f\n" +
	"\bshortcut\x18\x03 \x01(\tH\x00R\bshortcut\x88\x01\x01\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabledB\v\n" +
	"\t_shortcut\"\x9e\x02\n" +
	"\x0eUIEventRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12 \n" +
	"\taction_id\x18\x02 \x01(\tH\x00R\bactionId\x88\x01\x01\x12&\n" +
	"\fcomponent_id\x18\x03 \x01(\tH\x01R\vcomponentId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x123\n" +
	"\x04data\x18\x05 \x03(\v2\x1f.fenix.UIEventRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_action_idB\x0f\n" +
	"\r_component_id\"-\n" +
	"\x0fUIEventResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2O\n" +
	"\rHealthService\x12>\n" +
	"\x05Check\x12\x19.fenix.HealthCheckRequest\x1a\x1a.fenix.HealthCheckResponse2\x9c\x01\n" +
	"\rModuleService\x12D\n" +
	"\vListModules\x12\x19.fenix.ListModulesRequest\x1a\x1a.fenix.ListModulesResponse\x12E\n" +
	"\x0fGetModuleStatus\x12\x1d.fenix.GetModuleStatusRequest\x1a\x13.fenix.ModuleStatus2\x88\x01\n" +
	"\x0fUIStreamService\x129\n" +
	"\bStreamUI\x12\x16.fenix.UIStreamRequest\x1a\x13.fenix.UIViewUpdate0\x01\x12:\n" +
	"\tSendEvent\x12\x15.fenix.UIEventRequest\x1a\x16.fenix.UIEventResponseB%Z#github.com/mixa-ai/engine/pkg/protob\x06proto3"

var (
	file_fenix_proto_rawDescOnce sync.Once
	file_fenix_proto_rawDescData []byte
)

func file_fenix_proto_rawDescGZIP() []byte {
	file_fenix_proto_rawDescOnce.Do(func() {
		file_fenix_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fenix_proto_rawDesc), len(file_fenix_proto_rawDesc)))
	})
	return file_fenix_proto_rawDescData
}

var file_fenix_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_fenix_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),     // 0: fenix.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 1: fenix.HealthCheckResponse
	(*ListModulesRequest)(nil),     // 2: fenix.ListModulesRequest
	(*ListModulesResponse)(nil),    // 3: fenix.ListModulesResponse
	(*GetModuleStatusRequest)(nil), // 4: fenix.GetModuleStatusRequest
	(*ModuleStatus)(nil),           // 5: fenix.ModuleStatus
	(*UIStreamRequest)(nil),        // 6: fenix.UIStreamRequest
	(*UIViewUpdate)(nil),           // 7: fenix.UIViewUpdate
	(*UIComponent)(nil),            // 8: fenix.UIComponent
	(*TableColumn)(nil),            // 9: fenix.TableColumn
	(*RowData)(nil),                // 10: fenix.RowData
	(*Metric)(nil),                 // 11: fenix.Metric
	(*ChartDataPoint)(nil),         // 12: fenix.ChartDataPoint
	(*FormField)(nil),              // 13: fenix.FormField
	(*UIAction)(nil),               // 14: fenix.UIAction
	(*UIEventRequest)(nil),         // 15: fenix.UIEventRequest
	(*UIEventResponse)(nil),        // 16: fenix.UIEventResponse
	nil,                            // 17: fenix.RowData.ValuesEntry
	nil,                            // 18: fenix.ChartDataPoint.ValuesEntry
	nil,                            // 19: fenix.UIEventRequest.DataEntry
}
var file_fenix_proto_depIdxs = []int32{
	5,  // 0: fenix.ListModulesResponse.modules:type_name -> fenix.ModuleStatus
	8,  // 1: fenix.UIViewUpdate.components:type_name -> fenix.UIComponent
	14, // 2: fenix.UIViewUpdate.actions:type_name -> fenix.UIAction
	9,  // 3: fenix.UIComponent.columns:type_name -> fenix.TableColumn
	10, // 4: fenix.UIComponent.rows:type_name -> fenix.RowData
	11, // 5: fenix.UIComponent.metrics:type_name -> fenix.Metric
	12, // 6: fenix.UIComponent.chart_data:type_name -> fenix.ChartDataPoint
	13, // 7: fenix.UIComponent.fields:type_name -> fenix.FormField
	17, // 8: fenix.RowData.values:type_name -> fenix.RowData.ValuesEntry
	18, // 9: fenix.ChartDataPoint.values:type_name -> fenix.ChartDataPoint.ValuesEntry
	19, // 10: fenix.UIEventRequest.data:type_name -> fenix.UIEventRequest.DataEntry
	0,  // 11: fenix.HealthService.Check:input_type -> fenix.HealthCheckRequest
	2,  // 12: fenix.ModuleService.ListModules:input_type -> fenix.ListModulesRequest
	4,  // 13: fenix.ModuleService.GetModuleStatus:input_type -> fenix.GetModuleStatusRequest
	6,  // 14: fenix.UIStreamService.StreamUI:input_type -> fenix.UIStreamRequest
	15, // 15: fenix.UIStreamService.SendEvent:input_type -> fenix.UIEventRequest
	1,  // 16: fenix.HealthService.Check:output_type -> fenix.HealthCheckResponse
	3,  // 17: fenix.ModuleService.ListModules:output_type -> fenix.ListModulesResponse
	5,  // 18: fenix.ModuleService.GetModuleStatus:output_type -> fenix.ModuleStatus
	7,  // 19: fenix.UIStreamService.StreamUI:output_type -> fenix.UIViewUpdate
	16, // 20: fenix.UIStreamService.SendEvent:output_type -> fenix.UIEventResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_fenix_proto_init() }
func file_fenix_proto_init() {
	if File_fenix_proto != nil {
		return
	}
	file_fenix_proto_msgTypes[8].OneofWrappers = []any{}
	file_fenix_proto_msgTypes[9].OneofWrappers = []any{}
	file_fenix_proto_msgTypes[13].OneofWrappers = []any{}
	file_fenix_proto_msgTypes[14].OneofWrappers = []any{}
	file_fenix_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fenix_proto_rawDesc), len(file_fenix_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_fenix_proto_goTypes,
		DependencyIndexes: file_fenix_proto_depIdxs,
		MessageInfos:      file_fenix_proto_msgTypes,
	}.Build()
	File_fenix_proto = out.File
	file_fenix_proto_goTypes = nil
	file_fenix_proto_depIdxs = nil
}
