// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: fenix.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthService_Check_FullMethodName = "/fenix.HealthService/Check"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HealthService reports engine liveness and version info.
type HealthServiceClient interface {
	// Check returns the engine's current health status.
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, HealthService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServiceServer is the server API for HealthService service.
// All implementations must embed UnimplementedHealthServiceServer
// for forward compatibility.
//
// HealthService reports engine liveness and version info.
type HealthServiceServer interface {
	// Check returns the engine's current health status.
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedHealthServiceServer()
}

// UnimplementedHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServiceServer struct{}

func (UnimplementedHealthServiceServer) Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedHealthServiceServer) mustEmbedUnimplementedHealthServiceServer() {}
func (UnimplementedHealthServiceServer) testEmbeddedByValue()                       {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fenix.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _HealthService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fenix.proto",
}

const (
	ModuleService_ListModules_FullMethodName     = "/fenix.ModuleService/ListModules"
	ModuleService_GetModuleStatus_FullMethodName = "/fenix.ModuleService/GetModuleStatus"
)

// ModuleServiceClient is the client API for ModuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModuleService provides introspection into registered engine modules.
type ModuleServiceClient interface {
	// ListModules returns the status of all registered modules.
	ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error)
	// GetModuleStatus returns the status of a single module by name.
	GetModuleStatus(ctx context.Context, in *GetModuleStatusRequest, opts ...grpc.CallOption) (*ModuleStatus, error)
}

type moduleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModuleServiceClient(cc grpc.ClientConnInterface) ModuleServiceClient {
	return &moduleServiceClient{cc}
}

func (c *moduleServiceClient) ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModulesResponse)
	err := c.cc.Invoke(ctx, ModuleService_ListModules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) GetModuleStatus(ctx context.Context, in *GetModuleStatusRequest, opts ...grpc.CallOption) (*ModuleStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModuleStatus)
	err := c.cc.Invoke(ctx, ModuleService_GetModuleStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleServiceServer is the server API for ModuleService service.
// All implementations must embed UnimplementedModuleServiceServer
// for forward compatibility.
//
// ModuleService provides introspection into registered engine modules.
type ModuleServiceServer interface {
	// ListModules returns the status of all registered modules.
	ListModules(context.Context, *ListModulesRequest) (*ListModulesResponse, error)
	// GetModuleStatus returns the status of a single module by name.
	GetModuleStatus(context.Context, *GetModuleStatusRequest) (*ModuleStatus, error)
	mustEmbedUnimplementedModuleServiceServer()
}

// UnimplementedModuleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModuleServiceServer struct{}

func (UnimplementedModuleServiceServer) ListModules(context.Context, *ListModulesRequest) (*ListModulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModules not implemented")
}
func (UnimplementedModuleServiceServer) GetModuleStatus(context.Context, *GetModuleStatusRequest) (*ModuleStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModuleStatus not implemented")
}
func (UnimplementedModuleServiceServer) mustEmbedUnimplementedModuleServiceServer() {}
func (UnimplementedModuleServiceServer) testEmbeddedByValue()                       {}

// UnsafeModuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModuleServiceServer will
// result in compilation errors.
type UnsafeModuleServiceServer interface {
	mustEmbedUnimplementedModuleServiceServer()
}

func RegisterModuleServiceServer(s grpc.ServiceRegistrar, srv ModuleServiceServer) {
	// If the following call panics, it indicates UnimplementedModuleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModuleService_ServiceDesc, srv)
}

func _ModuleService_ListModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).ListModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_ListModules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).ListModules(ctx, req.(*ListModulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_GetModuleStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModuleStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).GetModuleStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_GetModuleStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).GetModuleStatus(ctx, req.(*GetModuleStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModuleService_ServiceDesc is the grpc.ServiceDesc for ModuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fenix.ModuleService",
	HandlerType: (*ModuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListModules",
			Handler:    _ModuleService_ListModules_Handler,
		},
		{
			MethodName: "GetModuleStatus",
			Handler:    _ModuleService_GetModuleStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fenix.proto",
}

const (
	UIStreamService_StreamUI_FullMethodName  = "/fenix.UIStreamService/StreamUI"
	UIStreamService_SendEvent_FullMethodName = "/fenix.UIStreamService/SendEvent"
)

// UIStreamServiceClient is the client API for UIStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UIStreamService is the core of the Fenix UI protocol. It allows engine
// modules to push structured UI updates to the renderer and receive user
// interaction events back.
type UIStreamServiceClient interface {
	// StreamUI opens a server-side stream. The engine pushes UIViewUpdate
	// messages whenever the active module's view changes.
	StreamUI(ctx context.Context, in *UIStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UIViewUpdate], error)
	// SendEvent delivers a user interaction (click, input, shortcut, scroll)
	// from the renderer back to the engine.
	SendEvent(ctx context.Context, in *UIEventRequest, opts ...grpc.CallOption) (*UIEventResponse, error)
}

type uIStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUIStreamServiceClient(cc grpc.ClientConnInterface) UIStreamServiceClient {
	return &uIStreamServiceClient{cc}
}

func (c *uIStreamServiceClient) StreamUI(ctx context.Context, in *UIStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UIViewUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UIStreamService_ServiceDesc.Streams[0], UIStreamService_StreamUI_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UIStreamRequest, UIViewUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UIStreamService_StreamUIClient = grpc.ServerStreamingClient[UIViewUpdate]

func (c *uIStreamServiceClient) SendEvent(ctx context.Context, in *UIEventRequest, opts ...grpc.CallOption) (*UIEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UIEventResponse)
	err := c.cc.Invoke(ctx, UIStreamService_SendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UIStreamServiceServer is the server API for UIStreamService service.
// All implementations must embed UnimplementedUIStreamServiceServer
// for forward compatibility.
//
// UIStreamService is the core of the Fenix UI protocol. It allows engine
// modules to push structured UI updates to the renderer and receive user
// interaction events back.
type UIStreamServiceServer interface {
	// StreamUI opens a server-side stream. The engine pushes UIViewUpdate
	// messages whenever the active module's view changes.
	StreamUI(*UIStreamRequest, grpc.ServerStreamingServer[UIViewUpdate]) error
	// SendEvent delivers a user interaction (click, input, shortcut, scroll)
	// from the renderer back to the engine.
	SendEvent(context.Context, *UIEventRequest) (*UIEventResponse, error)
	mustEmbedUnimplementedUIStreamServiceServer()
}

// UnimplementedUIStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUIStreamServiceServer struct{}

func (UnimplementedUIStreamServiceServer) StreamUI(*UIStreamRequest, grpc.ServerStreamingServer[UIViewUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamUI not implemented")
}
func (UnimplementedUIStreamServiceServer) SendEvent(context.Context, *UIEventRequest) (*UIEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedUIStreamServiceServer) mustEmbedUnimplementedUIStreamServiceServer() {}
func (UnimplementedUIStreamServiceServer) testEmbeddedByValue()                         {}

// UnsafeUIStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UIStreamServiceServer will
// result in compilation errors.
type UnsafeUIStreamServiceServer interface {
	mustEmbedUnimplementedUIStreamServiceServer()
}

func RegisterUIStreamServiceServer(s grpc.ServiceRegistrar, srv UIStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedUIStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UIStreamService_ServiceDesc, srv)
}

func _UIStreamService_StreamUI_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UIStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UIStreamServiceServer).StreamUI(m, &grpc.GenericServerStream[UIStreamRequest, UIViewUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UIStreamService_StreamUIServer = grpc.ServerStreamingServer[UIViewUpdate]

func _UIStreamService_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UIEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIStreamServiceServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIStreamService_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIStreamServiceServer).SendEvent(ctx, req.(*UIEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UIStreamService_ServiceDesc is the grpc.ServiceDesc for UIStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UIStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fenix.UIStreamService",
	HandlerType: (*UIStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _UIStreamService_SendEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUI",
			Handler:       _UIStreamService_StreamUI_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fenix.proto",
}
